# Generated by Django 5.2.13 on 2026-05-02 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column', models.CharField(choices=[('loved', 'Loved'), ('loathed', 'Loathed'), ('longed', 'Longed for'), ('learned', 'Learned')], max_length=16)),
                ('content', models.CharField(max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['column', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
