# Generated by Django 5.2.13 on 2026-05-02 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('retrospectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouped_cards', to='cards.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='retrospective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='retrospectives.retrospective'),
        ),
        migrations.AddField(
            model_name='cardvote',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cardvote',
            constraint=models.UniqueConstraint(fields=('card', 'voter'), name='unique_card_vote_per_voter'),
        ),
    ]
