# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
