# Generated by Django 5.2.13 on 2026-05-02 00:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('participant_joined', 'Participant joined')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('challenge', 'Challenge'), ('change', 'Change'), ('recognition', 'Recognition'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votes_remaining', models.IntegerField(default=3)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sprint_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('team_key', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('lobby', 'Lobby'), ('presentation', 'Presentation'), ('check', 'Check'), ('board', 'Board'), ('grouping', 'Grouping'), ('voting', 'Voting'), ('discussion', 'Discussion'), ('actions', 'Actions'), ('closed', 'Closed')], default='setup', max_length=20)),
                ('invite_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('invite_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_votes_per_user', models.PositiveSmallIntegerField(default=3)),
                ('skip_check_phase', models.BooleanField(default=False)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_paused_at', models.DateTimeField(blank=True, null=True)),
                ('timer_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
