# Generated by Django 5.2.13 on 2026-05-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_initial"),
        ("retrospectives", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrospective",
            name="focus_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="focused_in_retrospectives",
                to="cards.card",
            ),
        ),
    ]