# Generated by Django 5.2.13 on 2026-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospectives', '0003_retrospective_focus_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='invite_temporarily_open_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('participant_joined', 'Participant joined'), ('link_reopened', 'Link reopened'), ('link_auto_blocked', 'Link auto-blocked')], max_length=32),
        ),
    ]
