# Generated by Django 5.2.13 on 2026-05-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospectives', '0004_add_invite_temporarily_open_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='allow_self_vote',
            field=models.BooleanField(default=False),
        ),
    ]
