# Generated by Django 5.2.13 on 2026-05-02 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('cards', '0001_initial'),
        ('retrospectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='cards.card'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='retrospective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='retrospectives.retrospective'),
        ),
    ]
