# Generated by Django 5.2.13 on 2026-05-02 00:00

from django.db import migrations, models


def migrate_pending_to_not_started(apps, schema_editor):
    ActionItem = apps.get_model("actions", "ActionItem")
    ActionItem.objects.filter(status="pending").update(status="not_started")


def migrate_not_started_to_pending(apps, schema_editor):
    ActionItem = apps.get_model("actions", "ActionItem")
    ActionItem.objects.filter(status="not_started").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="external_tracker_url",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(migrate_pending_to_not_started, migrate_not_started_to_pending),
        migrations.AlterField(
            model_name="actionitem",
            name="status",
            field=models.CharField(
                choices=[("not_started", "Not started"), ("in_progress", "In progress"), ("done", "Done")],
                default="not_started",
                max_length=20,
            ),
        ),
    ]